### PR TITLE
Got rid of can_not_hold_a_reply error.

### LINKED ISSUE #78: can_not_hold_a_reply error for handle_call with {noreply, State} result
At the moment wpool does not work with gen_servers which return `{noreply, State}` in `handle_call`. Am I right that nothing is going to be broken in wpool If I change `{stop, can_not_hold_a_reply, State#state{state = NewState}};` to `{reply, queued, State#state{state = NewState}};` in the `wpool_process.erl`? From the first look everything is ok. I'm going to use this for semi-asynchronous sockets - successfuly sending of request will be acknowledged with `{noreply, State}` result of `gen_server:call()`, and actual reply to the transacton will be sent late with `gen_server:reply()`.

### PR DESCRIPTION
**Pull request by ElectronicRU**
Perhaps it had historical significance, but as of right now,
wpool_process uses ordinary gen_server reply facilities, and we can
safely pass on noreply results.

If a worker chose to handle a message later, then it is its own
responsibility, honestly.

Closes #78.

### CODE REVIEW

**Comment by ElectronicRU** [comment]
Well, 'course it does, cause it relies on that specific error for some reason. Either way, point taken.

**Comment by elbrujohalcon** [comment]
I get these errors when trying to run the tests on this branch now:

```erlang
===> Compiling _build/test/lib/worker_pool/test/wpool_process_SUITE.erl failed
_build/test/lib/worker_pool/test/wpool_process_SUITE.erl:214: syntax error before: 'after'

_build/test/lib/worker_pool/test/wpool_process_SUITE.erl:27: function stop/1 undefined
_build/test/lib/worker_pool/test/wpool_process_SUITE.erl:177: spec for undefined function stop/1
```

File: test/wpool_process_SUITE.erl [hunk 1]
```diff
@@ -207,25 +207,25 @@ stop(_Config) ->
   try wpool_process:call(stopper, {noreply, state}, 100) of
     _ -> ct:fail("unexpected response")
   catch
-    _:{can_not_hold_a_reply, _} -> ok
+    _:{timeout, _} -> ok
   end,
   receive
-    {'EXIT', Pid3, can_not_hold_a_reply} -> ok
+    {'EXIT', Pid3, _} -> ct:fail("Unexpected process crash"),
```
Comment (elbrujohalcon) [inline test/wpool_process_SUITE.erl]: There is an extra comma at the end of the row here.

File: test/wpool_process_SUITE.erl [hunk 2]
```diff
@@ -207,25 +207,25 @@ stop(_Config) ->
...
   {ok, Pid4} = wpool_process:start_link(stopper, echo_server, {ok, state}, []),
   try wpool_process:call(stopper, {noreply, state, hibernate}, 100) of
     _ -> ct:fail("unexpected response")
   catch
-    _:{can_not_hold_a_reply, _} -> ok
+    _:{timeout, _} -> ok
   end,
   receive
-    {'EXIT', Pid4, can_not_hold_a_reply} -> ok
+    {'EXIT', Pid3, _} -> ct:fail("Unexpected process crash"),
```
Comment (elbrujohalcon) [inline test/wpool_process_SUITE.erl]: There is an extra comma at the end of the row here.

**Comment by ElectronicRU** [comment]
Sorry, doing this between work, and sometimes a little too hasty 😓

File: test/wpool_process_SUITE.erl [hunk 3]
```diff
@@ -207,25 +207,25 @@ stop(_Config) ->
...
   receive
-    {'EXIT', Pid3, can_not_hold_a_reply} -> ok
+    {'EXIT', Pid3, _} -> ct:fail("Unexpected process crash")
   after 500 ->
-    ct:fail("Missing exit signal")
+    ok
   end,
 
   ct:comment("call with timeout stop"),
   {ok, Pid4} = wpool_process:start_link(stopper, echo_server, {ok, state}, []),
```
Comment (elbrujohalcon) [inline test/wpool_process_SUITE.erl]:
```erlang
variable 'Pid4' is unused
```

**Comment by elbrujohalcon** [comment]
@ElectronicRU I would love to merge your PR… could you please get `rebar3 ct` to work?
